/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programacion2.lab2progra2;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Airline extends javax.swing.JFrame {

    /**
     * Creates new form Airline
     */
    
    PalindromoAir palindromo;
    PalindromoAir pal = new PalindromoAir();
    Ticket ticketaire;
    
    private JComboBox<Ticket> listaPasajeros;
    
    ArrayList<Ticket> pasajeros = new ArrayList<>();
    
    public Airline() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        iniciarPaneles();
        
        
    }

    public void iniciarPaneles(){
        this.PanelMenuPrincipal.setVisible(true);
        this.PanelCompra.setVisible(false);
        this.PanelCancelar.setVisible(false);
        this.PanelVerPasajeros.setVisible(false);
        this.setLocation(300, 300);
        this.setSize(520, 480);
        
        listaPasajeros = new JComboBox<>(pasajeros.toArray(new Ticket[0]));
        
        JPanel ListaPasajeros = new JPanel();
        
        ListaPasajeros.add(listaPasajeros);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenuPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BotonDespacharVuelo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PanelCompra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        BotonComprar = new javax.swing.JButton();
        TituloFactura = new javax.swing.JLabel();
        labelCosto = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelTotalpagar = new javax.swing.JLabel();
        LabelCosto = new javax.swing.JLabel();
        LabelDescuento = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        BotonComprarRegresar = new javax.swing.JButton();
        PanelCancelar = new javax.swing.JPanel();
        NombreCancelar = new javax.swing.JLabel();
        CampoNombreCancelar = new javax.swing.JTextField();
        BotonCancelarTicket = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        EstadoCancelar = new javax.swing.JLabel();
        PanelVerPasajeros = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aerolineas  لنذهب مع الله");

        jButton1.setText("Comprar ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BotonDespacharVuelo.setText("Despachar vuelo");
        BotonDespacharVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDespacharVueloActionPerformed(evt);
            }
        });

        jButton4.setText("Ver pasajeros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuPrincipalLayout = new javax.swing.GroupLayout(PanelMenuPrincipal);
        PanelMenuPrincipal.setLayout(PanelMenuPrincipalLayout);
        PanelMenuPrincipalLayout.setHorizontalGroup(
            PanelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuPrincipalLayout.createSequentialGroup()
                .addGroup(PanelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuPrincipalLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(PanelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonDespacharVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelMenuPrincipalLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        PanelMenuPrincipalLayout.setVerticalGroup(
            PanelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuPrincipalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(BotonDespacharVuelo)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre: ");

        BotonComprar.setText("Comprar");
        BotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarActionPerformed(evt);
            }
        });

        TituloFactura.setText("Factura");

        labelCosto.setText("Costo:");

        labelDescuento.setText("Descuento:");

        labelTotalpagar.setText("Total a pagar:");

        LabelCosto.setText("jLabel7");

        LabelDescuento.setText("jLabel8");

        LabelTotal.setText("jLabel9");

        BotonComprarRegresar.setText("Regresar al menu");
        BotonComprarRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCompraLayout = new javax.swing.GroupLayout(PanelCompra);
        PanelCompra.setLayout(PanelCompraLayout);
        PanelCompraLayout.setHorizontalGroup(
            PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompraLayout.createSequentialGroup()
                .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCompraLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(TituloFactura))
                    .addGroup(PanelCompraLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonComprarRegresar)
                            .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelCompraLayout.createSequentialGroup()
                                    .addComponent(labelTotalpagar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotal))
                                .addGroup(PanelCompraLayout.createSequentialGroup()
                                    .addComponent(labelDescuento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelDescuento))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompraLayout.createSequentialGroup()
                                    .addComponent(labelCosto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelCosto))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompraLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotonComprar)
                                        .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        PanelCompraLayout.setVerticalGroup(
            PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompraLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonComprar)
                .addGap(44, 44, 44)
                .addComponent(TituloFactura)
                .addGap(18, 18, 18)
                .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCosto)
                    .addComponent(LabelCosto))
                .addGap(18, 18, 18)
                .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescuento)
                    .addComponent(LabelDescuento))
                .addGap(18, 18, 18)
                .addGroup(PanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalpagar)
                    .addComponent(LabelTotal))
                .addGap(18, 18, 18)
                .addComponent(BotonComprarRegresar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        NombreCancelar.setText("Ingrese el nombre: ");

        CampoNombreCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreCancelarActionPerformed(evt);
            }
        });

        BotonCancelarTicket.setText("Cancelar");
        BotonCancelarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarTicketActionPerformed(evt);
            }
        });

        jButton5.setText("Regresar al menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        EstadoCancelar.setText("jLabel3");

        javax.swing.GroupLayout PanelCancelarLayout = new javax.swing.GroupLayout(PanelCancelar);
        PanelCancelar.setLayout(PanelCancelarLayout);
        PanelCancelarLayout.setHorizontalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCancelarLayout.createSequentialGroup()
                .addGroup(PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCancelarLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreCancelar)
                            .addComponent(BotonCancelarTicket))
                        .addGroup(PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCancelarLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton5))
                            .addGroup(PanelCancelarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CampoNombreCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelCancelarLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(EstadoCancelar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelCancelarLayout.setVerticalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCancelarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCancelar)
                    .addComponent(CampoNombreCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(EstadoCancelar)
                .addGap(44, 44, 44)
                .addGroup(PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelarTicket)
                    .addComponent(jButton5))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jButton3.setText("Volver al menu");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout PanelVerPasajerosLayout = new javax.swing.GroupLayout(PanelVerPasajeros);
        PanelVerPasajeros.setLayout(PanelVerPasajerosLayout);
        PanelVerPasajerosLayout.setHorizontalGroup(
            PanelVerPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerPasajerosLayout.createSequentialGroup()
                .addGroup(PanelVerPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVerPasajerosLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton3))
                    .addGroup(PanelVerPasajerosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        PanelVerPasajerosLayout.setVerticalGroup(
            PanelVerPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVerPasajerosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(PanelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(PanelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelVerPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelVerPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.PanelMenuPrincipal.setVisible(false);
        this.PanelCompra.setVisible(true);
        TituloFactura.setText("Factura");
        TituloFactura.setVisible(false);
        labelCosto.setVisible(false);
        labelDescuento.setVisible(false);
        labelTotalpagar.setVisible(false);
        CampoNombre.setText("");
        LabelCosto.setVisible(false);
        LabelDescuento.setVisible(false);
        LabelTotal.setVisible(false);
        BotonComprarRegresar.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void BotonComprarRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarRegresarActionPerformed
        // TODO add your handling code here:
        this.PanelMenuPrincipal.setVisible(true);
        this.PanelCompra.setVisible(false);
        
    }//GEN-LAST:event_BotonComprarRegresarActionPerformed

    private void BotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarActionPerformed
        // TODO add your handling code here:
        pal.sellTicket(CampoNombre.getText());
            TituloFactura.setVisible(true);
            labelCosto.setVisible(true);
            labelDescuento.setVisible(true);
            labelTotalpagar.setVisible(true);
            LabelCosto.setVisible(true);
            LabelCosto.setText("800");
            LabelDescuento.setVisible(true);
            LabelTotal.setVisible(true);
            BotonComprarRegresar.setVisible(true);
            LabelDescuento.setText("0%");
            if (pal.price!=800){
                LabelDescuento.setText("20%");
            }
            LabelTotal.setText(Double.toString(pal.price));
    }//GEN-LAST:event_BotonComprarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.PanelCancelar.setVisible(true);
        this.PanelMenuPrincipal.setVisible(false);
        EstadoCancelar.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CampoNombreCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreCancelarActionPerformed

    private void BotonCancelarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarTicketActionPerformed
        // TODO add your handling code here:
        EstadoCancelar.setVisible(true);
        if(pal.cancelTicket(BotonCancelarTicket.getText())){
            EstadoCancelar.setText("Se ha cancelado el ticket.");
        }else{
            EstadoCancelar.setText("No se ha encontrado un ticket con el nombre.");
        }
        
    }//GEN-LAST:event_BotonCancelarTicketActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CampoNombreCancelar.setText("");
        EstadoCancelar.setText("");
        PanelCancelar.setVisible(false);
        PanelMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BotonDespacharVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDespacharVueloActionPerformed
        // TODO add your handling code here:
        pal.dispatch();
        JOptionPane.showMessageDialog(null,"Vuelo despachado con exito. Ganancias totales: "+pal.totalIncome );  
        
    }//GEN-LAST:event_BotonDespacharVueloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.PanelMenuPrincipal.setVisible(false);
        this.PanelVerPasajeros.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Airline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Airline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Airline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Airline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Airline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarTicket;
    private javax.swing.JButton BotonComprar;
    private javax.swing.JButton BotonComprarRegresar;
    private javax.swing.JButton BotonDespacharVuelo;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNombreCancelar;
    private javax.swing.JLabel EstadoCancelar;
    private javax.swing.JLabel LabelCosto;
    private javax.swing.JLabel LabelDescuento;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JLabel NombreCancelar;
    private javax.swing.JPanel PanelCancelar;
    private javax.swing.JPanel PanelCompra;
    private javax.swing.JPanel PanelMenuPrincipal;
    private javax.swing.JPanel PanelVerPasajeros;
    private javax.swing.JLabel TituloFactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelCosto;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelTotalpagar;
    // End of variables declaration//GEN-END:variables
}
